// -*- C++ -*- generated by wxGlade 0.5 on Thu May 10 17:15:52 2007 from /tdata/home/Desktop/stx-btree/trunk/wxbtreedemo/wxBTreeDemo.wxg

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WMAIN_WXG_H
#define WMAIN_WXG_H

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade

class WTreeDrawing;

class WMain_wxg: public wxFrame {
public:
    // begin wxGlade: WMain_wxg::ids
    enum {
        ID_BUTTON_INSERT = wxID_HIGHEST + 1000,
        ID_BUTTON_ERASE = wxID_HIGHEST + 1001,
        ID_BUTTON_INSERTRANDOM = wxID_HIGHEST + 1002,
        ID_BUTTON_CLEAR = wxID_HIGHEST + 1003
    };
    // end wxGlade

    WMain_wxg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: WMain_wxg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WMain_wxg::attributes
    wxStaticBox* sizer_4_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxChoice* choice_2;
    wxChoice* choice_2_copy;
    wxTextCtrl* textctrl_Key;
    wxTextCtrl* textctrl_Data;
    wxButton* button_Insert;
    wxButton* button_Erase;
    wxButton* button_InsertRandom;
    wxButton* button_3;
    wxButton* button_4;
    wxButton* button_Clear;
    wxTextCtrl* textctrl_OpResult;
    WTreeDrawing* window_TreeDrawing;
    wxPanel* notebook_1_pane_1;
    wxTextCtrl* textctrl_TextDump;
    wxPanel* notebook_1_pane_2;
    wxNotebook* notebook_1;
    // end wxGlade
}; // wxGlade: end class


#endif // WMAIN_WXG_H
